/**
 * HTML and Markdown templates for brainstorm output.
 *
 * Users can override the spec assembly template by placing a file at:
 *   ~/.insrc/templates/brainstorm-spec.md
 *
 * The file should contain a markdown template with placeholder sections
 * that the LLM will fill in. See BRAINSTORM_SPEC_TEMPLATE for the default.
 */

import { readFileSync } from 'node:fs';
import { PATHS } from '../../../shared/paths.js';
import { join } from 'node:path';

// ---------------------------------------------------------------------------
// HTML template
// ---------------------------------------------------------------------------

export const BRAINSTORM_HTML_TEMPLATE = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{{title}} — Brainstorm Spec</title>
  <style>
    :root {
      --bg: #1a1b26; --fg: #c0caf5; --accent: #7aa2f7;
      --border: #3b4261; --card: #24283b; --muted: #565f89;
      --green: #9ece6a; --yellow: #e0af68; --red: #f7768e;
      --purple: #bb9af7;
    }
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Inter', system-ui, sans-serif; background: var(--bg); color: var(--fg); line-height: 1.6; }
    .container { max-width: 960px; margin: 0 auto; padding: 2rem; }
    h1 { color: var(--accent); font-size: 1.8rem; margin-bottom: 0.5rem; }
    h2 { color: var(--purple); font-size: 1.3rem; margin: 2rem 0 0.75rem; border-bottom: 1px solid var(--border); padding-bottom: 0.3rem; }
    h3 { color: var(--fg); font-size: 1.1rem; margin: 1.2rem 0 0.5rem; }
    .subtitle { color: var(--muted); margin-bottom: 2rem; }
    .stats { display: flex; gap: 1.5rem; flex-wrap: wrap; margin: 1rem 0; }
    .stat { background: var(--card); border: 1px solid var(--border); border-radius: 8px; padding: 0.75rem 1.25rem; }
    .stat-value { font-size: 1.4rem; font-weight: 700; color: var(--accent); }
    .stat-label { font-size: 0.8rem; color: var(--muted); text-transform: uppercase; }
    .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 0.75rem; font-weight: 600; text-transform: uppercase; }
    .badge-must { background: rgba(247,118,142,0.15); color: var(--red); }
    .badge-should { background: rgba(224,175,104,0.15); color: var(--yellow); }
    .badge-could { background: rgba(158,206,106,0.15); color: var(--green); }
    .badge-functional { background: rgba(122,162,247,0.15); color: var(--accent); }
    .badge-nonfunctional { background: rgba(187,154,247,0.15); color: var(--purple); }
    .badge-constraint { background: rgba(224,175,104,0.15); color: var(--yellow); }
    .req-card { background: var(--card); border: 1px solid var(--border); border-radius: 8px; padding: 1rem; margin: 0.75rem 0; }
    .req-statement { font-weight: 500; margin-bottom: 0.5rem; }
    .req-meta { font-size: 0.85rem; color: var(--muted); }
    .criteria-list { margin: 0.5rem 0; padding-left: 1.5rem; }
    .criteria-list li { margin: 0.25rem 0; font-size: 0.9rem; }
    .theme-section { margin: 1.5rem 0; }
    .idea-item { padding: 0.4rem 0; font-size: 0.9rem; border-bottom: 1px solid var(--border); }
    .idea-status { font-size: 0.75rem; font-weight: 600; }
    .idea-status.promoted { color: var(--green); }
    .idea-status.accepted { color: var(--accent); }
    .idea-status.parked { color: var(--yellow); }
    .idea-status.rejected { color: var(--red); }
    .idea-status.merged { color: var(--purple); }
    .trace-table { width: 100%; border-collapse: collapse; margin: 1rem 0; font-size: 0.85rem; }
    .trace-table th, .trace-table td { padding: 0.5rem; border: 1px solid var(--border); text-align: left; }
    .trace-table th { background: var(--card); color: var(--muted); text-transform: uppercase; font-size: 0.75rem; }
    .revision-log { font-size: 0.85rem; color: var(--muted); }
    .revision-log li { margin: 0.3rem 0; }
  </style>
</head>
<body>
<div class="container">
  <h1>{{title}}</h1>
  <p class="subtitle">Brainstorm Specification — Generated by insrc</p>

  {{stats}}

  <h2>Problem Statement</h2>
  {{problem}}

  {{themes_section}}

  {{requirements_section}}

  {{traceability}}

  {{parked_ideas}}

  {{revision_log}}

  {{session_stats}}
</div>
</body>
</html>`;

// ---------------------------------------------------------------------------
// Markdown template
// ---------------------------------------------------------------------------

export const BRAINSTORM_MD_TEMPLATE = `# {{title}}

*Brainstorm Specification — Generated by insrc*

{{stats}}

## Problem Statement

{{problem}}

{{themes_section}}

{{requirements_section}}

{{traceability}}

{{parked_ideas}}

{{revision_log}}

{{session_stats}}`;

// ---------------------------------------------------------------------------
// Spec assembly template (used in ASSEMBLE_SPEC_SYSTEM prompt)
// ---------------------------------------------------------------------------

export const BRAINSTORM_SPEC_TEMPLATE = `# Requirements Specification — {{doc_id}}

> **Problem:** <restate the original problem in one sentence>

## Executive Summary

<2–3 sentences: what is being built, how many themes/requirements, key design decisions>

---

## 1. {{theme_id}} — <Theme Name>

> <theme description — one sentence>

| ID | Type | Priority | Requirement |
|----|------|----------|-------------|
| R-001 | functional | must | <requirement statement> |
| R-002 | functional | should | <requirement statement> |

### Acceptance Criteria

**R-001**
- [ ] <testable criterion 1>
- [ ] <testable criterion 2>

**R-002**
- [ ] <testable criterion 1>

---

## 2. <Next Theme Name>

> <theme description>

| ID | Type | Priority | Requirement |
|----|------|----------|-------------|
| R-003 | non-functional | must | <requirement statement> |

### Acceptance Criteria

**R-003**
- [ ] <testable criterion 1>

---

## Cross-References

| Requirement | Related To | Relationship |
|-------------|-----------|--------------|
| R-001 | R-003 | <brief explanation> |

---

## Traceability

| ID | Source Ideas | Theme |
|----|-------------|-------|
| R-001 | [1], [3] | <theme name> |
| R-002 | [5] | <theme name> |

---

## Open Questions

- <any ambiguities or gaps that need stakeholder input>

---

## Changelog

| Version | Date | Author | Changes |
|---------|------|--------|---------|
| 1.0 | {{date}} | {{author}} | Initial draft — {{theme_count}} themes, {{req_count}} requirements |`;

// ---------------------------------------------------------------------------
// Per-theme spec section template
// ---------------------------------------------------------------------------

export const BRAINSTORM_THEME_SPEC_TEMPLATE = `| ID | Type | Priority | Requirement | Source Ideas |
|----|------|----------|-------------|--------------|
| 1 | functional | must | <requirement statement> | [1], [3] |
| 2 | non-functional | should | <requirement statement> | [5] |

### Acceptance Criteria

**1**
- [ ] <testable criterion 1>
- [ ] <testable criterion 2>

**2**
- [ ] <testable criterion 1>`;

// ---------------------------------------------------------------------------
// Template loader — user override from ~/.insrc/templates/
// ---------------------------------------------------------------------------

const SPEC_TEMPLATE_FILE = 'brainstorm-spec.md';
const THEME_TEMPLATE_FILE = 'brainstorm-theme-spec.md';

/**
 * Load the spec assembly template.
 * Checks ~/.insrc/templates/brainstorm-spec.md first, falls back to built-in.
 */
export function loadSpecTemplate(): string {
  try {
    return readFileSync(join(PATHS.templates, SPEC_TEMPLATE_FILE), 'utf-8');
  } catch {
    return BRAINSTORM_SPEC_TEMPLATE;
  }
}

/**
 * Load the per-theme spec section template.
 * Checks ~/.insrc/templates/brainstorm-theme-spec.md first, falls back to built-in.
 */
export function loadThemeSpecTemplate(): string {
  try {
    return readFileSync(join(PATHS.templates, THEME_TEMPLATE_FILE), 'utf-8');
  } catch {
    return BRAINSTORM_THEME_SPEC_TEMPLATE;
  }
}
