/**
 * Ant Design classifier (`antd`).
 */

import type { LibraryClassifier } from './types.js';

export const ANTD: LibraryClassifier = {
	id: 'antd',
	importSources: ['antd', 'antd/es', 'antd/lib'],
	layoutContainers: {
		'Layout':        { direction: 'column' },
		'Layout.Header': { direction: 'row', region: 'header' },
		'Layout.Sider':  { direction: 'column', region: 'sidebar' },
		'Layout.Content':{ direction: 'column', region: 'content' },
		'Layout.Footer': { direction: 'row', region: 'footer' },
		'Header':        { direction: 'row', region: 'header' },
		'Sider':         { direction: 'column', region: 'sidebar' },
		'Content':       { direction: 'column', region: 'content' },
		'Footer':        { direction: 'row', region: 'footer' },
		'Row':           { direction: 'row' },
		'Col':           { direction: 'column' },
		'Space':         { direction: 'row' },
		'Flex':          { direction: 'row' },
		'Card':          { direction: 'column' },
	},
	semanticElements: {
		'Button':      { kind: 'placeholder', labelPrefix: 'Button' },
		'Input':       { kind: 'placeholder', labelPrefix: 'Input' },
		'Input.TextArea':{ kind: 'placeholder', labelPrefix: 'Input' },
		'Input.Search':{ kind: 'placeholder', labelPrefix: 'Search' },
		'TextArea':    { kind: 'placeholder', labelPrefix: 'Input' },
		'Select':      { kind: 'placeholder', labelPrefix: 'Select' },
		'AutoComplete':{ kind: 'placeholder', labelPrefix: 'Autocomplete' },
		'Cascader':    { kind: 'placeholder', labelPrefix: 'Select' },
		'Checkbox':    { kind: 'placeholder', labelPrefix: 'Checkbox' },
		'Radio':       { kind: 'placeholder', labelPrefix: 'Radio' },
		'Switch':      { kind: 'placeholder', labelPrefix: 'Toggle' },
		'Slider':      { kind: 'placeholder', labelPrefix: 'Slider' },
		'DatePicker':  { kind: 'placeholder', labelPrefix: 'DatePicker' },
		'TimePicker':  { kind: 'placeholder', labelPrefix: 'TimePicker' },
		'Upload':      { kind: 'placeholder', labelPrefix: 'Upload' },
		'Form':        { kind: 'placeholder', labelPrefix: 'Form' },
		'Form.Item':   { kind: 'placeholder', labelPrefix: 'FormField' },
		'Avatar':      { kind: 'placeholder', labelPrefix: 'Avatar' },
		'Badge':       { kind: 'placeholder', labelPrefix: 'Badge' },
		'Tag':         { kind: 'placeholder', labelPrefix: 'Tag' },
		'Typography':  { kind: 'placeholder', labelPrefix: 'Text' },
		'Typography.Title': { kind: 'placeholder', labelPrefix: 'Heading' },
		'Typography.Text':  { kind: 'placeholder', labelPrefix: 'Text' },
		'Typography.Paragraph': { kind: 'placeholder', labelPrefix: 'Text' },
		'Divider':     { kind: 'placeholder', labelPrefix: 'Divider' },
		'List':        { kind: 'placeholder', labelPrefix: 'List' },
		'List.Item':   { kind: 'placeholder', labelPrefix: 'Item' },
		'Table':       { kind: 'placeholder', labelPrefix: 'Table' },
		'Tabs':        { kind: 'placeholder', labelPrefix: 'Tabs' },
		'Tabs.TabPane':{ kind: 'placeholder', labelPrefix: 'Tab' },
		'Modal':       { kind: 'placeholder', labelPrefix: 'Dialog' },
		'Drawer':      { kind: 'placeholder', labelPrefix: 'Drawer' },
		'Popover':     { kind: 'placeholder', labelPrefix: 'Popover' },
		'Tooltip':     { kind: 'placeholder', labelPrefix: 'Tooltip' },
		'Menu':        { kind: 'placeholder', labelPrefix: 'Menu' },
		'Menu.Item':   { kind: 'placeholder', labelPrefix: 'Item' },
		'Breadcrumb':  { kind: 'placeholder', labelPrefix: 'Breadcrumb' },
		'Steps':       { kind: 'placeholder', labelPrefix: 'Steps' },
		'Alert':       { kind: 'placeholder', labelPrefix: 'Alert' },
		'Spin':        { kind: 'placeholder', labelPrefix: 'Spinner' },
		'Image':       { kind: 'placeholder', labelPrefix: 'Image' },
	},
};
