/**
 * Chakra UI classifier (`@chakra-ui/react`).
 */

import type { LibraryClassifier } from './types.js';

export const CHAKRA: LibraryClassifier = {
	id: 'chakra',
	importSources: ['@chakra-ui/react', '@chakra-ui/core'],
	layoutContainers: {
		'Stack':      { direction: 'column' },
		'VStack':     { direction: 'column' },
		'HStack':     { direction: 'row' },
		'Wrap':       { direction: 'row' },
		'Flex':       { direction: 'row' },
		'Center':     { direction: 'column' },
		'SimpleGrid': { direction: 'grid', colsProp: 'columns', defaultCols: 2 },
		'Grid':       { direction: 'grid', colsProp: 'templateColumns', defaultCols: 2 },
		'Box':        { direction: 'column' },
		'Container':  { direction: 'column' },
		'Card':       { direction: 'column' },
		'CardHeader': { direction: 'row', region: 'header' },
		'CardBody':   { direction: 'column' },
		'CardFooter': { direction: 'row', region: 'footer' },
	},
	semanticElements: {
		'Button':       { kind: 'placeholder', labelPrefix: 'Button' },
		'IconButton':   { kind: 'placeholder', labelPrefix: 'Icon' },
		'Input':        { kind: 'placeholder', labelPrefix: 'Input' },
		'NumberInput':  { kind: 'placeholder', labelPrefix: 'Input' },
		'Textarea':     { kind: 'placeholder', labelPrefix: 'Input' },
		'Select':       { kind: 'placeholder', labelPrefix: 'Select' },
		'Checkbox':     { kind: 'placeholder', labelPrefix: 'Checkbox' },
		'Radio':        { kind: 'placeholder', labelPrefix: 'Radio' },
		'Switch':       { kind: 'placeholder', labelPrefix: 'Toggle' },
		'Slider':       { kind: 'placeholder', labelPrefix: 'Slider' },
		'Avatar':       { kind: 'placeholder', labelPrefix: 'Avatar' },
		'Tag':          { kind: 'placeholder', labelPrefix: 'Tag' },
		'Badge':        { kind: 'placeholder', labelPrefix: 'Badge' },
		'Heading':      { kind: 'placeholder', labelPrefix: 'Heading' },
		'Text':         { kind: 'placeholder', labelPrefix: 'Text' },
		'Link':         { kind: 'placeholder', labelPrefix: 'Link' },
		'Divider':      { kind: 'placeholder', labelPrefix: 'Divider' },
		'List':         { kind: 'placeholder', labelPrefix: 'List' },
		'ListItem':     { kind: 'placeholder', labelPrefix: 'Item' },
		'Table':        { kind: 'placeholder', labelPrefix: 'Table' },
		'Tabs':         { kind: 'placeholder', labelPrefix: 'Tabs' },
		'Tab':          { kind: 'placeholder', labelPrefix: 'Tab' },
		'Modal':        { kind: 'placeholder', labelPrefix: 'Dialog' },
		'Drawer':       { kind: 'placeholder', labelPrefix: 'Drawer' },
		'Popover':      { kind: 'placeholder', labelPrefix: 'Popover' },
		'Tooltip':      { kind: 'placeholder', labelPrefix: 'Tooltip' },
		'Menu':         { kind: 'placeholder', labelPrefix: 'Menu' },
		'MenuItem':     { kind: 'placeholder', labelPrefix: 'Item' },
		'Alert':        { kind: 'placeholder', labelPrefix: 'Alert' },
		'Spinner':      { kind: 'placeholder', labelPrefix: 'Spinner' },
		'Image':        { kind: 'placeholder', labelPrefix: 'Image' },
	},
};
