import { readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import type { DesignTemplate } from './types.js';

// ---------------------------------------------------------------------------
// Built-in Design Templates
// ---------------------------------------------------------------------------

const DEFAULT_MD: DesignTemplate = {
  id: 'default-md',
  format: 'markdown',
  skeleton: `# {{title}}

## Overview

{{overview}}

## Requirements Summary

{{requirements_summary}}

{{requirement_sections}}

## Architecture Summary

{{architecture_summary}}

## Risks & Open Questions

{{risks}}
`,
  sections: [
    {
      id: 'overview',
      heading: 'Overview',
      guidance: 'A 2-3 sentence summary of what is being designed and why.',
    },
    {
      id: 'requirements_summary',
      heading: 'Requirements Summary',
      guidance: 'Numbered list of validated requirements with type (FUNCTIONAL/SYSTEM) and status (done/skipped).',
    },
    {
      id: 'requirement_section',
      heading: '### Requirement {{index}}: {{statement}}',
      guidance: 'Detailed design for this requirement including interface contracts, data flow, integration points, migration notes, and risks.',
    },
    {
      id: 'architecture_summary',
      heading: 'Architecture Summary',
      guidance: 'High-level summary of proposed new entities, reused entities, and how they connect.',
    },
    {
      id: 'risks',
      heading: 'Risks & Open Questions',
      guidance: 'Consolidated risks and unresolved decisions across all requirements.',
    },
  ],
  builtin: true,
};

const DEFAULT_HTML: DesignTemplate = {
  id: 'default-html',
  format: 'html',
  skeleton: `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{{title}} — Design Document</title>
  <style>{{css}}</style>
</head>
<body>
  <main>
    <h1>{{title}}</h1>
    <p class="muted">Generated by insrc Designer Agent</p>

    <h2>Overview</h2>
    {{overview}}

    <h2>Requirements Summary</h2>
    {{requirements_summary}}

    {{requirement_sections}}

    <h2>Architecture Summary</h2>
    {{architecture_summary}}

    <h2>Risks &amp; Open Questions</h2>
    {{risks}}
  </main>
</body>
</html>`,
  sections: DEFAULT_MD.sections,
  css: `:root {
  --bg: #0f1117;
  --surface: #1a1d27;
  --border: #2a2d3a;
  --text: #e2e4ed;
  --muted: #8b8fa8;
  --accent: #7c6af7;
  --accent2: #4fc3f7;
  --green: #4caf7d;
  --yellow: #f5c842;
  --code-bg: #12151e;
  font-family: 'Segoe UI', system-ui, sans-serif;
  font-size: 15px;
}

* { box-sizing: border-box; margin: 0; padding: 0; }

body {
  background: var(--bg);
  color: var(--text);
  line-height: 1.7;
  padding: 2rem;
}

main {
  max-width: 960px;
  margin: 0 auto;
}

h1 { font-size: 2rem; color: var(--accent); margin-bottom: 0.25rem; }
h2 { font-size: 1.3rem; color: var(--accent2); margin: 2.5rem 0 0.75rem; border-bottom: 1px solid var(--border); padding-bottom: 0.4rem; }
h3 { font-size: 1.05rem; color: var(--yellow); margin: 1.5rem 0 0.5rem; }
p { margin: 0.6rem 0; }
.muted { color: var(--muted); font-size: 0.9rem; }

pre {
  background: var(--code-bg);
  border: 1px solid var(--border);
  border-radius: 6px;
  padding: 1rem;
  overflow-x: auto;
  font-size: 0.88rem;
  margin: 0.8rem 0;
}

code { font-family: 'Fira Code', 'Consolas', monospace; }

ul, ol { margin: 0.5rem 0; padding-left: 1.5rem; }
li { margin: 0.2rem 0; }

table { width: 100%; border-collapse: collapse; margin: 1rem 0; }
th, td { border: 1px solid var(--border); padding: 0.5rem 0.8rem; text-align: left; }
th { background: var(--surface); color: var(--accent2); font-size: 0.9rem; }`,
  builtin: true,
};

export const BUILTIN_TEMPLATES: Record<string, DesignTemplate> = {
  'default-md':   DEFAULT_MD,
  'default-html': DEFAULT_HTML,
};

// ---------------------------------------------------------------------------
// Template resolution
// ---------------------------------------------------------------------------

/**
 * Resolve a design template.
 *
 * Resolution order:
 *   1. --template <id> flag (explicit template ID)
 *   2. Project-level template in <repoPath>/.insrc/templates/design-default.{md,html}
 *   3. Built-in default-md or default-html
 */
export function resolveTemplate(opts: {
  format?: 'markdown' | 'html';
  templateId?: string | undefined;
  repoPath?: string | undefined;
}): DesignTemplate {
  // 1. Explicit template ID
  if (opts.templateId) {
    // Check builtins first
    if (opts.templateId in BUILTIN_TEMPLATES) {
      return BUILTIN_TEMPLATES[opts.templateId]!;
    }
    // Check project templates
    if (opts.repoPath) {
      const custom = loadProjectTemplate(opts.repoPath, opts.templateId);
      if (custom) return custom;
    }
    // Fall through to default if not found (don't error — degrade gracefully)
  }

  const format = opts.format ?? 'markdown';

  // 2. Project-level override
  if (opts.repoPath) {
    const ext = format === 'html' ? 'html' : 'md';
    const custom = loadProjectTemplate(opts.repoPath, `design-default.${ext}`);
    if (custom) return custom;
  }

  // 3. Built-in default
  return format === 'html' ? DEFAULT_HTML : DEFAULT_MD;
}

// ---------------------------------------------------------------------------
// Project template loading
// ---------------------------------------------------------------------------

/**
 * Load a template from the project's .insrc/templates/ directory.
 * Returns null if the file doesn't exist or is invalid.
 */
function loadProjectTemplate(repoPath: string, id: string): DesignTemplate | null {
  const templatePath = join(repoPath, '.insrc', 'templates', id);
  if (!existsSync(templatePath)) return null;

  try {
    const content = readFileSync(templatePath, 'utf8');
    const isHtml = id.endsWith('.html');

    return {
      id,
      format: isHtml ? 'html' : 'markdown',
      skeleton: content,
      sections: DEFAULT_MD.sections, // Project templates reuse default sections
      builtin: false,
    };
  } catch {
    return null;
  }
}

// ---------------------------------------------------------------------------
// Template flag parsing
// ---------------------------------------------------------------------------

/**
 * Extract --template and --html flags from a user message.
 * Returns the cleaned message and extracted options.
 */
export function parseTemplateFlags(message: string): {
  message: string;
  format?: 'markdown' | 'html';
  templateId?: string;
} {
  let format: 'markdown' | 'html' | undefined;
  let templateId: string | undefined;
  let cleaned = message;

  // --html flag
  if (/--html\b/.test(cleaned)) {
    format = 'html';
    cleaned = cleaned.replace(/--html\b/, '').trim();
  }

  // --template <id> flag
  const templateMatch = cleaned.match(/--template\s+(\S+)/);
  if (templateMatch) {
    templateId = templateMatch[1];
    cleaned = cleaned.replace(/--template\s+\S+/, '').trim();
  }

  const result: { message: string; format?: 'markdown' | 'html'; templateId?: string } = { message: cleaned };
  if (format !== undefined) result.format = format;
  if (templateId !== undefined) result.templateId = templateId;
  return result;
}
