/**
 * Types for the Pair coding agent — collaborative multi-turn coding.
 *
 * Pair operates in a fluid propose → review → refine loop without
 * an upfront plan. Supports implement, refactor, debug, and explore modes.
 */

import type { ProviderOverride } from '../../framework/provider-mention.js';

// ---------------------------------------------------------------------------
// Input
// ---------------------------------------------------------------------------

/** Input from the REPL to start a pair coding session. */
export interface PairInput {
  message: string;
  codeContext: string;
  designSpec?: string | undefined;
  mode: PairMode;
  session: {
    repoPath: string;
    closureRepos: string[];
  };
}

export type PairMode = 'implement' | 'refactor' | 'debug' | 'explore';

// ---------------------------------------------------------------------------
// Working state entities
// ---------------------------------------------------------------------------

/** A diff that was applied to disk. */
export interface DiffEntry {
  file: string;
  diff: string;
  appliedAt: string;
}

/** A TODO item in a multi-step proposal. */
export interface TodoItem {
  index: number;
  description: string;
  status: 'pending' | 'in_progress' | 'done' | 'skipped';
  diff?: string | undefined;
}

/** A proposal generated by the agent for user review. */
export interface Proposal {
  summary: string;
  diff?: string | undefined;
  todos?: TodoItem[] | undefined;
  findings?: Finding[] | undefined;
  question?: string | undefined;
}

/** A finding from code investigation (debug/explore modes). */
export interface Finding {
  description: string;
  evidence: string;
  file?: string | undefined;
  line?: number | undefined;
}

/** A hypothesis for debugging. */
export interface Hypothesis {
  id: string;
  description: string;
  status: 'pending' | 'confirmed' | 'rejected';
  evidence: string;
}

// ---------------------------------------------------------------------------
// Result
// ---------------------------------------------------------------------------

/** Final output of the pair agent. */
export interface PairResult {
  kind: 'pair-coding';
  filesChanged: string[];
  changesApplied: DiffEntry[];
  summary: string;
  mode: PairMode;
}

// ---------------------------------------------------------------------------
// Re-export shared types
// ---------------------------------------------------------------------------

export type { ProviderOverride };
